메인페이지 퍼블리싱
OPENMIND-TFT/OPENMIND pull request #54
Opened 2024-01-20 10:05 UTC by jinyoung1018

## 🛠️주요 변경 사항

-메인 페이지 퍼블리싱

## 📣리뷰어에게 하고싶은 말

-

## ❗관련이슈

- closed: #6

## 🖼️스크린샷(선택)
<img width="841" alt="image" src="https://github.com/OPENMIND-TFT/OPENMIND/assets/71465981/cb14c2d0-0a25-44e7-bc96-d3157164a1ae">

2024-01-20 10:18 UTC, DanteSnow requested changes

2024-01-20 10:18 UTC, DanteSnow commented on src/pages/MainPage/index.js
클래스네임 케밥케이스로 바꿔주세용!

그리고 시맨틱 태그도 잘 지켜주시면 좋을 것 같아요! 👍🏻

2024-01-20 10:18 UTC, DanteSnow commented on src/pages/MainPage/index.js
아 그리고 이미지 확장자명은 png말고 svg를 사용해야 픽셀 깨지는 현상이 없다고 들었어요.
png는 브라우저 크기에 따라서 픽셀이 많이 깨진다고 하네요.
그래서 웬만하면 이미지는 svg로 사용한다고 해요! 👍🏻

2024-01-20 10:23 UTC, nyaknya commented on src/pages/MainPage/index.js
> +      <div className="buttonArea">
코드 컨벤션 정한 것 중에 클래스명은 kebab-case로 하기로 해서, 전체적으로 className을 해당 케이스로 바꾸면 좋을 것 같습니다!

2024-01-20 10:23 UTC, nyaknya commented on src/pages/MainPage/index.js
> +        <img
이것에 대해 좋은 글 하나를 참조드려요.
https://inseq.co.kr/ko/bbs/i-24/show.do?seq=19
배경에 있는 사람들 이미지 같은 경우는 제가 판단하기에 꾸밈 요소 같아서, img 태그보단 background-img로 처리해주는게 더 적절하지 않나 의견 달아봅니다! 진영님, 또는 다른 분들도 판단 해주시고 피드백 부탁드려요~

2024-01-20 10:30 UTC, nyaknya commented on src/pages/MainPage/index.js
> +      <img className="logoImage" src="/assets/images/logo.png" alt="로고" />
리액트 라우터의 Link를 활용해 감싸서 메인으로 빠지는 코드를 추가하면 좋을 것 같습니다! 같은 페이지로 이동하는 거라 새로고침 되는 셈이긴 하지만 다른 곳에 들어가는 로고들은 일괄적으로 메인으로 이동하는 링크를 가지고 있을 테니까요~

2024-01-20 10:49 UTC, haeyong9701 approved these changes

2024-01-20 10:49 UTC, haeyong9701 commented on src/pages/MainPage/style.js
> +    button {
tag에 직접 스타일을 주면 유지보수가 힘들어 질 수 있어요!

2024-01-20 12:35 UTC, mocking-tiger commented on src/pages/MainPage/style.js
> +      border-color: var(--Brown-40);
컬러 그냥 수치로 바로 입력하고 있었는데 이거보고 함수가 있다는게 생각났어요!
저도 바로 수정해야겠네요 감사합니다^^

2024-01-20 13:22 UTC, jinyoung1018 commented on src/pages/MainPage/index.js
03a24ea71c9316b029c1894bba29ba1eb7fdb9b9 클래스네임은 케밥케이스인거 깜빡했네용 수정했습니다!
69e00c76643faf02cd41985ccd4792c8093a94be 기존에 있던 파일들 제외하고 제가 새로 추가한 이미지 파일은 svg형식으로 다시 다운받아서 수정했습니다!

2024-01-20 13:23 UTC, jinyoung1018 commented on src/pages/MainPage/index.js
> +      <div className="buttonArea">
03a24ea71c9316b029c1894bba29ba1eb7fdb9b9  이 부분 깜빡했네용 수정했습니다!

2024-01-20 13:25 UTC, jinyoung1018 commented on src/pages/MainPage/index.js
> +      <img className="logoImage" src="/assets/images/logo.png" alt="로고" />
8d9c9c427e8176c9ae322d30fa4cd8fb57856211 추가했습니당!

2024-01-20 13:29 UTC, jinyoung1018 commented on src/pages/MainPage/style.js
> +    button {
스타일드 컴포넌트의 장점이 클래스네임을 고민하지 않아도 되는거라고 해서 저는 각 div마다 클래스네임을 지정해주고 그 안에 있는 요소들은 겹치는 요소가 없다면 해당 태그에 바로 스타일을 주었는데, 모두 다 클래스네임을 지정해줘야 하는걸까용??

2024-01-20 13:29 UTC, jinyoung1018 commented on src/pages/MainPage/style.js
> +      border-color: var(--Brown-40);
오옹 좋습니당!!

2024-01-20 13:35 UTC, jinyoung1018 commented on src/pages/MainPage/index.js
> +        <img
7922b7ff89641753fe0098c49260096500907b52 알려주신 방법으로 수정해봤는데, 저는 이렇게 하면 이미지가 안뜨네요ㅜㅜ 뭐가 잘못된걸까요??

2024-01-20 14:47 UTC, DanteSnow commented on src/pages/MainPage/style.js
> +    button {
음.. 지금은 페이지에 들어가는 코드도 많지 않아서 괜찮기는 할 것 같은데요!
페이지에 기능들이 많이 들어가서 button 사용이 많아지면 결국엔 클래스네임을 나눠야 하니까 습관을 들여놓는 게 좋을 것 같아요!
스타일 컴포넌트라서 저는 취향 차이라고 생각하는데, 다른 분들은 어떻게 생각하시나요?!

2024-01-20 14:50 UTC, DanteSnow approved these changes

2024-01-20 14:51 UTC, merged

2024-01-20 15:09 UTC, haeyong9701 commented on src/pages/MainPage/style.js
> +    button {
하나의 파일 안에서도 div 태그의 하위 태그들이 많아지게 된다면 겹치는 요소들도 많아져서 미리 className을 작성하는 거라고 생각을 해요. 지금은 겹치는 요소가 없다는 부분을 인지하고 있지만 나중에 코드를 리팩토링하거나 다른 팀원들이 개발할 때 헷갈릴 수 있을 것 같아요.

2024-01-21 10:19 UTC, nyaknya commented on src/pages/MainPage/index.js
> +        <img
진영님! 닫힌 PR이지만 코멘트 다는게 될까 싶어 올려봅니다... 혹시 css를 어떻게 작성하셨을까요?!

2024-01-22 10:57 UTC, haeyong9701 commented on src/pages/MainPage/style.js
> +    button {
닫힌 PR이지만 알림이 갈거 같아서 여기에 코멘트 달아봐요.

멘토님께 '모두 다 클래스네임을 지정해줘야 될까요?' 라는 질문을 남겼는데 멘토님이 하신 답변이 전혀 이해가 되지 않아서
주강사님께 다시 물어봤습니다.

'스타일드 컴포넌트 파일 안에서 모두 다 클래스네임을 지정해줘야 될까요?'
<img width="223" alt="스크린샷 2024-01-22 오후 7 50 34" src="https://github.com/OPENMIND-TFT/OPENMIND/assets/72595163/7688dc2e-d54c-4ea4-b1c6-6156429c1160">

스타일드 컴포넌트나 SCSS는 전역쪽이나 부모 태그쪽에는 클래스 네임을 적어야 되겠지만, 자식 태그에는 클래스 네임을 꼭 쓸 필요가 없다고 합니다. 이런 부분은 치현님이 말씀하신대로 취향 차이라고 하셨어요. 

저는 무조건 클래스 네임을 다 적어야 줘야 하는줄 알았는데 제가 잘못된 생각을 가지고 있었네요.. 잘못된 부분으로 피드백해서 죄송합니다...

2024-01-22 11:01 UTC, mocking-tiger commented on src/pages/MainPage/style.js
> +    button {
이런 경험 또한 서로 코드리뷰를 주고 받으면서 알게된 사실이니까 죄송하실 필요는 없을것 같습니다! 다같이 하나 배운거죠 ^^ 감사합니다!!