메인페이지 기능구현
OPENMIND-TFT/OPENMIND pull request #96
Opened 2024-01-23 06:33 UTC by jinyoung1018

## 🛠️주요 변경 사항

- 답변하기 클릭시 서버에 피드 생성
- 생성된 피드 아이디로 /post/${id}/answer 경로 이동
- 질문하기 버튼 클릭시 리스트 페이지로 이동

## 📣리뷰어에게 하고싶은 말

-

## ❗관련이슈

- closed: #9 

## 🖼️스크린샷(선택)

2024-01-23 06:40 UTC, DanteSnow approved these changes
역시 너무 잘하시네요!! 부럽습니다.. ㅎㅎ 👍🏻
고생 많으셨구, 저희 api 따로 빼기로 했었는데 이 부분만 한 번 확인해주세요!🫡

2024-01-23 08:16 UTC, nyaknya requested changes

2024-01-23 08:16 UTC, nyaknya commented on src/pages/MainPage/index.js
> +          <button type="button">질문 하러 가기 {'->'}</button>
제 화면에만 그런진 모르겠는데, 질문 하러 가기 버튼이 이렇게 깨져보입니다...! 
![image](https://github.com/OPENMIND-TFT/OPENMIND/assets/49646127/83be0c52-5d8a-47d2-b333-148e1b0a1d0f)

2024-01-23 08:16 UTC, nyaknya commented on src/pages/MainPage/index.js
> +        <img
이 부분 저번에 여쭤보신것같은데 대답을 못해드려서 ㅠㅠ 도움되는건 아니지만 참조가 될까하여 제 코드에서 몇가지 가져왔습니다!
`    background: url(/assets/images/logoWithoutBg.png) no-repeat center bottom;`
이렇게 지정하면 이미지 태그 없이도 배경 지정이 가능할것같아요..!

2024-01-23 08:17 UTC, nyaknya commented
(기능 수정 부분이 아니라 따로 달아놓습니다.) 테스트 해봤는데 메인 화면에서 엔터로도 질문 잘 전송되고 POST 보내는 기능이 잘 작동하는 것 같습니다! 진영님 수고 많으셨어요~~!

2024-01-23 08:21 UTC, haeyong9701 approved these changes
기능 구현 빠르게 잘 해주신 것 같아요!

2024-01-23 08:21 UTC, haeyong9701 commented on src/api.js
> +}
.json() 이 비동기가 아니기도 하고, 새로 변수 선언해서 return할 필요는 따로 없어 보여요!

```
return response.json();
```

이런 식으로 줄일 수 있을 것 같습니다

2024-01-23 08:21 UTC, haeyong9701 commented on src/pages/MainPage/index.js
> +    console.log({ name });
`console.log`는 이제 없어져도 될 거 같아요.

2024-01-23 08:45 UTC, mocking-tiger approved these changes
확인했습니다 제가 보기엔 잘 하신것 같아요!

2024-01-24 02:06 UTC, nyaknya approved these changes

2024-01-24 02:11 UTC, merged